### ISSUE TITLE
Flee cannot be executed in combat

### ISSUE THREAD

**Issue by dmbyer** [dmbyer/Hedron#22]
When a player is in combat, flee cannot be executed even though that is the only time it should be a valid state. This bug was discovered when the player was in combat with themselves, which is another bug. It's possible resolving that will also correct this issue.

**Comment by MattTheDev** [comment]
I have a fix for this - but wanted to get your thoughts before I clean it up, and submit the PR.

I've modified CommandHandler.ProcessCommand to take a list of valid states .. it checks if the command entered is within the valid states, and if so .. executes. If not, it then HandleCombatInput.

**Comment by dmbyer** [comment]
The state check logic is actually in the command's Execute method in Command.cs line 78/79:
`			// Check state
			if (!ValidStates.Contains(args.Entity.StateHandler.State))
				throw new StateException();
`

The derived class (the command itself, e.g. "flee") overrides the Execute method, calls the parent which handles the state check, and then the command itself should catch the state exception. Not sure where the logic may have gone wrong there.

**Comment by dmbyer** [comment]
As a side note, now that I am looking at this, all of the // TODO comments in the Execute method were also completed. Forgot to clean those up.

**Comment by dmbyer** [comment]
I think I actually see what you are saying now. I may have designed this improperly for separation of concerns. I wonder if HandleCombatInput might need a bit of a rework. It makes sense that the state check should happen in CommandHandler and not the command itself. The Command could have a property, or maybe a new state error class etc., that stores specific messages for a command when an the entity is in an invalid state. Then the CommandHandler could call that unique message from the command if the state is invalid. Just a thought.

**Comment by dmbyer** [comment]
I also had a plan to add a queue for commands when a player was in combat -- I stumbled across this when working on skills just now. If a "kick" skill should not be executed as frequently as a player wants to type it, then it would require a queue (and a cooldown, which I'm adding into the skill class). HandleCombatInput would probably need to be expanded to make use of a queue. I think I failed to document my plan thoroughly enough ages ago when I wrote this...

**Comment by MattTheDev** [comment]
Created draft #26 to show what I did to "make it work" .. however, the rework makes sense. I think if it works the way it is, but the queuing sounds more on par what I've seen in other MUDs out there.

Appreciate you letting me drop in here every so often and contribute .. its nice when I need to reset my brain.

**Comment by dmbyer** [comment]
Resolved with ea39cc0
